// db/migrations/005_expand_plants_catalog.js
//
// SUPERSEDED — not registered in run.js.
//
// This draft expanded the catalog but assigned images from opaque Unsplash
// IDs (which caused the Onion→potato mismatch and duplicated placeholders),
// and left overview/agronomy/pests/resources empty for every crop.
//
// The authoritative catalog now lives in db/catalog/plant-catalog.json and
// is applied by 006_apply_verified_plant_catalog.js, which enforces
// verified Wikimedia Commons images (descriptive filenames, URL-probed) and
// full per-crop detail data. On a fresh database 006 creates the entire
// 64-crop catalog, so this draft is never run.
//
// Kept for historical reference only.

function tableExists(db, name) {
  return Boolean(
    db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name = ?").get(name)
  );
}

const EXPANDED_PLANTS = [
  // === CEREALS (existing: rice, wheat, maize) ===
  {
    slug: 'sorghum',
    name: 'Sorghum (Jowar)',
    scientific_name: 'Sorghum bicolor',
    category: 'Cereals',
    season: 'Kharif',
    water_need: 'Low',
    climate: 'Tropical',
    region: 'Maharashtra, Karnataka, Tamil Nadu',
    duration: '100–120 days',
    expected_yield: '2.0–2.5 tons/acre',
    difficulty: 'Easy',
    profitability: 'Medium',
    market_price: '₹2,000–2,500/quintal',
    image_url: 'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=400&h=300&fit=crop',
    description: 'Drought-tolerant cereal grain used for food, feed, and biofuel production.',
  },
  {
    slug: 'pearl_millet',
    name: 'Pearl Millet (Bajra)',
    scientific_name: 'Pennisetum glaucum',
    category: 'Cereals',
    season: 'Kharif',
    water_need: 'Very Low',
    climate: 'Tropical',
    region: 'Rajasthan, Gujarat, Haryana',
    duration: '80–90 days',
    expected_yield: '1.5–2.0 tons/acre',
    difficulty: 'Easy',
    profitability: 'Medium',
    market_price: '₹2,200–2,800/quintal',
    image_url: 'https://images.unsplash.com/photo-1635363638580-c2809d049eee?w=400&h=300&fit=crop',
    description: 'Hardy cereal adapted to arid and semi-arid regions; excellent drought resistance.',
  },
  {
    slug: 'finger_millet',
    name: 'Finger Millet (Ragi)',
    scientific_name: 'Eleusine coracana',
    category: 'Cereals',
    season: 'Kharif',
    water_need: 'Low',
    climate: 'Tropical',
    region: 'Karnataka, Tamil Nadu, Uttarakhand',
    duration: '100–120 days',
    expected_yield: '1.5–2.0 tons/acre',
    difficulty: 'Easy',
    profitability: 'Medium',
    market_price: '₹3,000–3,500/quintal',
    image_url: 'https://images.unsplash.com/photo-1614059205754-79d2e1e4f30a?w=400&h=300&fit=crop',
    description: 'Nutrient-rich millet high in calcium; ideal for health-conscious consumers.',
  },
  {
    slug: 'barley',
    name: 'Barley (Jau)',
    scientific_name: 'Hordeum vulgare',
    category: 'Cereals',
    season: 'Rabi',
    water_need: 'Low',
    climate: 'Temperate',
    region: 'Rajasthan, UP, Haryana, Punjab',
    duration: '120–150 days',
    expected_yield: '2.0–2.5 tons/acre',
    difficulty: 'Easy',
    profitability: 'Medium',
    market_price: '₹1,800–2,200/quintal',
    image_url: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=400&h=300&fit=crop',
    description: 'Versatile cereal used for food, feed, and malting; tolerates saline soils.',
  },
  {
    slug: 'oats',
    name: 'Oats',
    scientific_name: 'Avena sativa',
    category: 'Cereals',
    season: 'Rabi',
    water_need: 'Medium',
    climate: 'Temperate',
    region: 'Punjab, HP, J&K',
    duration: '100–120 days',
    expected_yield: '1.5–2.0 tons/acre',
    difficulty: 'Easy',
    profitability: 'Medium',
    market_price: '₹2,500–3,000/quintal',
    image_url: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=400&h=300&fit=crop',
    description: 'Cool-season cereal with growing health food market; good forage crop.',
  },

  // === PULSES (new category) ===
  {
    slug: 'chickpea',
    name: 'Chickpea (Chana)',
    scientific_name: 'Cicer arietinum',
    category: 'Pulses',
    season: 'Rabi',
    water_need: 'Low',
    climate: 'Temperate',
    region: 'MP, Rajasthan, Maharashtra',
    duration: '100–120 days',
    expected_yield: '1.0–1.5 tons/acre',
    difficulty: 'Easy',
    profitability: 'High',
    market_price: '₹5,000–6,500/quintal',
    image_url: 'https://images.unsplash.com/photo-1515543237350-b3eea1ec8082?w=400&h=300&fit=crop',
    description: 'Major pulse crop; nitrogen-fixing legume important for food security.',
  },
  {
    slug: 'pigeon_pea',
    name: 'Pigeon Pea (Arhar)',
    scientific_name: 'Cajanus cajan',
    category: 'Pulses',
    season: 'Kharif',
    water_need: 'Medium',
    climate: 'Tropical',
    region: 'Maharashtra, MP, Karnataka',
    duration: '150–180 days',
    expected_yield: '0.8–1.2 tons/acre',
    difficulty: 'Medium',
    profitability: 'Medium',
    market_price: '₹6,000–7,500/quintal',
    image_url: 'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=400&h=300&fit=crop',
    description: 'Important perennial pulse; excellent intercrop with cereals.',
  },
  {
    slug: 'green_gram',
    name: 'Green Gram (Moong)',
    scientific_name: 'Vigna radiata',
    category: 'Pulses',
    season: 'Kharif',
    water_need: 'Low',
    climate: 'Tropical',
    region: 'Pan-India',
    duration: '60–70 days',
    expected_yield: '0.6–0.8 tons/acre',
    difficulty: 'Easy',
    profitability: 'High',
    market_price: '₹7,000–9,000/quintal',
    image_url: 'https://images.unsplash.com/photo-1612257416648-ee7a4d709a24?w=400&h=300&fit=crop',
    description: 'Short-duration pulse; excellent for crop rotation and green manure.',
  },
  {
    slug: 'black_gram',
    name: 'Black Gram (Urad)',
    scientific_name: 'Vigna mungo',
    category: 'Pulses',
    season: 'Kharif',
    water_need: 'Medium',
    climate: 'Tropical',
    region: 'UP, MP, Maharashtra',
    duration: '75–90 days',
    expected_yield: '0.5–0.7 tons/acre',
    difficulty: 'Easy',
    profitability: 'High',
    market_price: '₹8,000–10,000/quintal',
    image_url: 'https://images.unsplash.com/photo-1583557965739-1a30f0a3b996?w=400&h=300&fit=crop',
    description: 'Premium pulse crop; essential ingredient in dal and fermented foods.',
  },
  {
    slug: 'lentil',
    name: 'Lentil (Masoor)',
    scientific_name: 'Lens culinaris',
    category: 'Pulses',
    season: 'Rabi',
    water_need: 'Low',
    climate: 'Temperate',
    region: 'UP, MP, Bihar',
    duration: '110–130 days',
    expected_yield: '0.8–1.0 tons/acre',
    difficulty: 'Easy',
    profitability: 'Medium',
    market_price: '₹5,500–7,000/quintal',
    image_url: 'https://images.unsplash.com/photo-1583557965739-1a30f0a3b996?w=400&h=300&fit=crop',
    description: 'Cool-season pulse; excellent source of protein for vegetarian diets.',
  },
  {
    slug: 'cowpea',
    name: 'Cowpea (Lobia)',
    scientific_name: 'Vigna unguiculata',
    category: 'Pulses',
    season: 'Kharif',
    water_need: 'Low',
    climate: 'Tropical',
    region: 'Rajasthan, Gujarat, UP',
    duration: '60–75 days',
    expected_yield: '0.5–0.8 tons/acre',
    difficulty: 'Easy',
    profitability: 'Medium',
    market_price: '₹4,000–5,500/quintal',
    image_url: 'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=400&h=300&fit=crop',
    description: 'Heat-tolerant pulse; excellent for dryland farming systems.',
  },

  // === OILSEEDS (existing: groundnut) ===
  {
    slug: 'soybean',
    name: 'Soybean',
    scientific_name: 'Glycine max',
    category: 'Oil Seeds',
    season: 'Kharif',
    water_need: 'Medium',
    climate: 'Tropical',
    region: 'MP, Maharashtra, Rajasthan',
    duration: '90–100 days',
    expected_yield: '1.0–1.2 tons/acre',
    difficulty: 'Medium',
    profitability: 'High',
    market_price: '₹4,000–5,000/quintal',
    image_url: 'https://images.unsplash.com/photo-1599420186946-7b6fb4e297f0?w=400&h=300&fit=crop',
    description: 'Major oilseed and protein crop; essential for oil and animal feed.',
  },
  {
    slug: 'mustard',
    name: 'Mustard (Sarson)',
    scientific_name: 'Brassica juncea',
    category: 'Oil Seeds',
    season: 'Rabi',
    water_need: 'Low',
    climate: 'Temperate',
    region: 'Rajasthan, Haryana, UP',
    duration: '110–140 days',
    expected_yield: '0.8–1.0 tons/acre',
    difficulty: 'Easy',
    profitability: 'Medium',
    market_price: '₹4,500–5,500/quintal',
    image_url: 'https://images.unsplash.com/photo-1560493676-04071c5f467b?w=400&h=300&fit=crop',
    description: 'Primary oilseed crop of India; bright yellow flowers indicate harvest time.',
  },
  {
    slug: 'sesame',
    name: 'Sesame (Til)',
    scientific_name: 'Sesamum indicum',
    category: 'Oil Seeds',
    season: 'Kharif',
    water_need: 'Low',
    climate: 'Tropical',
    region: 'Gujarat, MP, Rajasthan',
    duration: '80–90 days',
    expected_yield: '0.4–0.6 tons/acre',
    difficulty: 'Easy',
    profitability: 'High',
    market_price: '₹12,000–15,000/quintal',
    image_url: 'https://images.unsplash.com/photo-1509627584448-9e4534aea053?w=400&h=300&fit=crop',
    description: 'High-value oilseed; excellent export potential for oil and seeds.',
  },
  {
    slug: 'sunflower',
    name: 'Sunflower',
    scientific_name: 'Helianthus annuus',
    category: 'Oil Seeds',
    season: 'Rabi',
    water_need: 'Medium',
    climate: 'Temperate',
    region: 'Karnataka, AP, Maharashtra',
    duration: '90–100 days',
    expected_yield: '0.8–1.0 tons/acre',
    difficulty: 'Medium',
    profitability: 'Medium',
    market_price: '₹6,000–7,000/quintal',
    image_url: 'https://images.unsplash.com/photo-1597848212624-a19eb35e2651?w=400&h=300&fit=crop',
    description: 'Popular oilseed with high oleic acid content; attracts pollinators.',
  },
  {
    slug: 'castor',
    name: 'Castor',
    scientific_name: 'Ricinus communis',
    category: 'Oil Seeds',
    season: 'Kharif',
    water_need: 'Medium',
    climate: 'Tropical',
    region: 'Gujarat, Rajasthan, AP',
    duration: '120–150 days',
    expected_yield: '1.0–1.5 tons/acre',
    difficulty: 'Medium',
    profitability: 'High',
    market_price: '₹4,500–5,500/quintal',
    image_url: 'https://images.unsplash.com/photo-1592841200221-a6898f307baa?w=400&h=300&fit=crop',
    description: 'Industrial oilseed; castor oil used in pharmaceuticals and cosmetics.',
  },
  {
    slug: 'linseed',
    name: 'Linseed (Flax)',
    scientific_name: 'Linum usitatissimum',
    category: 'Oil Seeds',
    season: 'Rabi',
    water_need: 'Low',
    climate: 'Temperate',
    region: 'MP, Rajasthan, UP',
    duration: '100–120 days',
    expected_yield: '0.5–0.7 tons/acre',
    difficulty: 'Easy',
    profitability: 'Medium',
    market_price: '₹5,000–6,000/quintal',
    image_url: 'https://images.unsplash.com/photo-1607431953732-0a462a3d0a1?w=400&h=300&fit=crop',
    description: 'Dual-purpose crop for oil and fiber; rich in omega-3 fatty acids.',
  },

  // === VEGETABLES (existing: tomato, onion) ===
  {
    slug: 'potato',
    name: 'Potato',
    scientific_name: 'Solanum tuberosum',
    category: 'Vegetables',
    season: 'Rabi',
    water_need: 'Medium',
    climate: 'Temperate',
    region: 'UP, WB, Bihar',
    duration: '90–120 days',
    expected_yield: '8–12 tons/acre',
    difficulty: 'Medium',
    profitability: 'High',
    market_price: '₹1,000–1,800/quintal',
    image_url: 'https://images.unsplash.com/photo-1518977676601-b53f82ber946?w=400&h=300&fit=crop',
    description: 'Major tuber crop; fourth most important food crop globally.',
  },
  {
    slug: 'onion',
    name: 'Onion',
    scientific_name: 'Allium cepa',
    category: 'Vegetables',
    season: 'Rabi + Kharif',
    water_need: 'Medium',
    climate: 'Temperate',
    region: 'Maharashtra, Karnataka, MP',
    duration: '90–150 days',
    expected_yield: '10–15 tons/acre',
    difficulty: 'Medium',
    profitability: 'High',
    market_price: '₹1,200–2,500/quintal',
    image_url: 'https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?w=400&h=300&fit=crop',
    description: 'High-value bulb crop with strong domestic demand and export potential.',
  },
  {
    slug: 'garlic',
    name: 'Garlic',
    scientific_name: 'Allium sativum',
    category: 'Vegetables',
    season: 'Rabi',
    water_need: 'Low',
    climate: 'Temperate',
    region: 'MP, Rajasthan, Gujarat',
    duration: '130–150 days',
    expected_yield: '2.0–3.0 tons/acre',
    difficulty: 'Medium',
    profitability: 'Very High',
    market_price: '₹8,000–12,000/quintal',
    image_url: 'https://images.unsplash.com/photo-1615477550925-8e0b1e322567?w=400&h=300&fit=crop',
    description: 'High-value spice crop; essential ingredient in cuisines worldwide.',
  },
  {
    slug: 'okra',
    name: 'Okra (Bhindi)',
    scientific_name: 'Abelmoschus esculentus',
    category: 'Vegetables',
    season: 'Kharif',
    water_need: 'Medium',
    climate: 'Tropical',
    region: 'Pan-India',
    duration: '50–65 days',
    expected_yield: '3.0–5.0 tons/acre',
    difficulty: 'Easy',
    profitability: 'High',
    market_price: '₹1,500–3,000/quintal',
    image_url: 'https://images.unsplash.com/photo-1501004318855-ac0c2ce12a07?w=400&h=300&fit=crop',
    description: 'Popular warm-season vegetable; continuous harvesting over 2–3 months.',
  },
  {
    slug: 'brinjal',
    name: 'Brinjal (Eggplant)',
    scientific_name: 'Solanum melongena',
    category: 'Vegetables',
    season: 'Kharif',
    water_need: 'Medium',
    climate: 'Tropical',
    region: 'Pan-India',
    duration: '75–90 days',
    expected_yield: '8–12 tons/acre',
    difficulty: 'Medium',
    profitability: 'High',
    market_price: '₹1,200–2,000/quintal',
    image_url: 'https://images.unsplash.com/photo-1615484477778-ca3b77940c25?w=400&h=300&fit=crop',
    description: 'Versatile vegetable with many varieties; high in fiber and antioxidants.',
  },
  {
    slug: 'cauliflower',
    name: 'Cauliflower',
    scientific_name: 'Brassica oleracea var. botrytis',
    category: 'Vegetables',
    season: 'Rabi',
    water_need: 'Medium',
    climate: 'Temperate',
    region: 'UP, MP, WB',
    duration: '90–120 days',
    expected_yield: '8–12 tons/acre',
    difficulty: 'Hard',
    profitability: 'High',
    market_price: '₹1,500–3,000/quintal',
    image_url: 'https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=400&h=300&fit=crop',
    description: 'Cool-season cole crop; sensitive to heat and frost during curd formation.',
  },
  {
    slug: 'cabbage',
    name: 'Cabbage',
    scientific_name: 'Brassica oleracea var. capitata',
    category: 'Vegetables',
    season: 'Rabi',
    water_need: 'Medium',
    climate: 'Temperate',
    region: 'UP, MP, HP',
    duration: '90–120 days',
    expected_yield: '10–15 tons/acre',
    difficulty: 'Medium',
    profitability: 'Medium',
    market_price: '₹800–1,500/quintal',
    image_url: 'https://images.unsplash.com/photo-1594282486756-7e4b10e8e9a5?w=400&h=300&fit=crop',
    description: 'Hardy cole crop; good source of vitamins and minerals.',
  },
  {
    slug: 'carrot',
    name: 'Carrot',
    scientific_name: 'Daucus carota',
    category: 'Vegetables',
    season: 'Rabi',
    water_need: 'Medium',
    climate: 'Temperate',
    region: 'HP, Punjab, UP',
    duration: '70–90 days',
    expected_yield: '6–8 tons/acre',
    difficulty: 'Easy',
    profitability: 'Medium',
    market_price: '₹1,500–2,500/quintal',
    image_url: 'https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=400&h=300&fit=crop',
    description: 'Root vegetable rich in beta-carotene; cool-season crop.',
  },
  {
    slug: 'peas',
    name: 'Green Peas',
    scientific_name: 'Pisum sativum',
    category: 'Vegetables',
    season: 'Rabi',
    water_need: 'Medium',
    climate: 'Temperate',
    region: 'UP, MP, HP',
    duration: '60–75 days',
    expected_yield: '2.0–3.0 tons/acre',
    difficulty: 'Easy',
    profitability: 'High',
    market_price: '₹3,000–5,000/quintal',
    image_url: 'https://images.unsplash.com/photo-1587735243615-c03f25aaff15?w=400&h=300&fit=crop',
    description: 'Popular cool-season vegetable; nitrogen-fixing legume.',
  },
  {
    slug: 'capsicum',
    name: 'Capsicum (Bell Pepper)',
    scientific_name: 'Capsicum annuum',
    category: 'Vegetables',
    season: 'Kharif',
    water_need: 'Medium',
    climate: 'Tropical',
    region: 'Pan-India',
    duration: '70–90 days',
    expected_yield: '4.0–6.0 tons/acre',
    difficulty: 'Medium',
    profitability: 'High',
    market_price: '₹2,000–4,000/quintal',
    image_url: 'https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=400&h=300&fit=crop',
    description: 'Colorful vegetable rich in vitamins; multiple harvests per season.',
  },
  {
    slug: 'chili',
    name: 'Chili Pepper',
    scientific_name: 'Capsicum annuum',
    category: 'Vegetables',
    season: 'Kharif',
    water_need: 'Medium',
    climate: 'Tropical',
    region: 'Andhra Pradesh, Telangana',
    duration: '90–120 days',
    expected_yield: '1.0–1.5 tons/acre',
    difficulty: 'Medium',
    profitability: 'Very High',
    market_price: '₹8,000–15,000/quintal',
    image_url: 'https://images.unsplash.com/photo-1583119022894-919a68a3d0e3?w=400&h=300&fit=crop',
    description: 'High-value spice crop; essential in Indian and international cuisines.',
  },
  {
    slug: 'cucumber',
    name: 'Cucumber',
    scientific_name: 'Cucumis sativus',
    category: 'Vegetables',
    season: 'Kharif',
    water_need: 'High',
    climate: 'Tropical',
    region: 'Pan-India',
    duration: '50–65 days',
    expected_yield: '6–8 tons/acre',
    difficulty: 'Easy',
    profitability: 'Medium',
    market_price: '₹1,000–2,000/quintal',
    image_url: 'https://images.unsplash.com/photo-1449300079323-02e209d9d3a6?w=400&h=300&fit=crop',
    description: 'Refreshing summer vegetable; high water content and quick maturing.',
  },
  {
    slug: 'bitter_gourd',
    name: 'Bitter Gourd (Karela)',
    scientific_name: 'Momordica charantia',
    category: 'Vegetables',
    season: 'Kharif',
    water_need: 'Medium',
    climate: 'Tropical',
    region: 'Pan-India',
    duration: '60–75 days',
    expected_yield: '3.0–4.0 tons/acre',
    difficulty: 'Medium',
    profitability: 'High',
    market_price: '₹2,000–4,000/quintal',
    image_url: 'https://images.unsplash.com/photo-1573246123716-6b1782bfc499?w=400&h=300&fit=crop',
    description: 'Medicinal vegetable; valued for health benefits and unique flavor.',
  },
  {
    slug: 'bottle_gourd',
    name: 'Bottle Gourd (Lauki)',
    scientific_name: 'Lagenaria siceraria',
    category: 'Vegetables',
    season: 'Kharif',
    water_need: 'High',
    climate: 'Tropical',
    region: 'Pan-India',
    duration: '60–75 days',
    expected_yield: '8–12 tons/acre',
    difficulty: 'Easy',
    profitability: 'Medium',
    market_price: '₹800–1,500/quintal',
    image_url: 'https://images.unsplash.com/photo-1590005024862-6b67679a29fb?w=400&h=300&fit=crop',
    description: 'Climbing vine producing long gourds; used in curries and juices.',
  },
  {
    slug: 'ridge_gourd',
    name: 'Ridge Gourd (Turai)',
    scientific_name: 'Luffa acutangula',
    category: 'Vegetables',
    season: 'Kharif',
    water_need: 'Medium',
    climate: 'Tropical',
    region: 'Pan-India',
    duration: '55–65 days',
    expected_yield: '4.0–6.0 tons/acre',
    difficulty: 'Easy',
    profitability: 'Medium',
    market_price: '₹1,000–2,000/quintal',
    image_url: 'https://images.unsplash.com/photo-1590005024862-6b67679a29fb?w=400&h=300&fit=crop',
    description: 'Fast-growing vine vegetable; excellent for summer gardens.',
  },
  {
    slug: 'pumpkin',
    name: 'Pumpkin',
    scientific_name: 'Cucurbita moschata',
    category: 'Vegetables',
    season: 'Kharif',
    water_need: 'Medium',
    climate: 'Tropical',
    region: 'Pan-India',
    duration: '90–120 days',
    expected_yield: '8–12 tons/acre',
    difficulty: 'Easy',
    profitability: 'Medium',
    market_price: '₹600–1,200/quintal',
    image_url: 'https://images.unsplash.com/photo-1506484289740-da908b3a6e60?w=400&h=300&fit=crop',
    description: 'Large vining vegetable; stores well for months after harvest.',
  },
  {
    slug: 'sweet_potato',
    name: 'Sweet Potato',
    scientific_name: 'Ipomoea batatas',
    category: 'Vegetables',
    season: 'Kharif',
    water_need: 'Medium',
    climate: 'Tropical',
    region: 'UP, WB, Bihar',
    duration: '100–120 days',
    expected_yield: '6–8 tons/acre',
    difficulty: 'Easy',
    profitability: 'Medium',
    market_price: '₹1,500–2,500/quintal',
    image_url: 'https://images.unsplash.com/photo-1596097635121-14b63a7b70b5?w=400&h=300&fit=crop',
    description: 'Nutritious tuber crop; high in vitamins and dietary fiber.',
  },
  {
    slug: 'yam',
    name: 'Yam',
    scientific_name: 'Dioscorea alata',
    category: 'Vegetables',
    season: 'Kharif',
    water_need: 'Medium',
    climate: 'Tropical',
    region: 'Kerala, Tamil Nadu, UP',
    duration: '150–180 days',
    expected_yield: '4.0–6.0 tons/acre',
    difficulty: 'Medium',
    profitability: 'Medium',
    market_price: '₹2,000–3,500/quintal',
    image_url: 'https://images.unsplash.com/photo-1518977676601-b53f82ber946?w=400&h=300&fit=crop',
    description: 'Staple tuber in tropical regions; good source of carbohydrates.',
  },

  // === SPICES (new category) ===
  {
    slug: 'turmeric',
    name: 'Turmeric (Haldi)',
    scientific_name: 'Curcuma longa',
    category: 'Spices',
    season: 'Kharif',
    water_need: 'Medium',
    climate: 'Tropical',
    region: 'Tamil Nadu, AP, Maharashtra',
    duration: '240–270 days',
    expected_yield: '3.0–4.0 tons/acre',
    difficulty: 'Medium',
    profitability: 'Very High',
    market_price: '₹8,000–12,000/quintal',
    image_url: 'https://images.unsplash.com/photo-1615485500704-8e990f9900f7?w=400&h=300&fit=crop',
    description: 'Golden spice with medicinal properties; used in cooking and traditional medicine.',
  },
  {
    slug: 'ginger',
    name: 'Ginger',
    scientific_name: 'Zingiber officinale',
    category: 'Spices',
    season: 'Kharif',
    water_need: 'High',
    climate: 'Tropical',
    region: 'Kerala, Meghalaya, AP',
    duration: '240–270 days',
    expected_yield: '4.0–6.0 tons/acre',
    difficulty: 'Medium',
    profitability: 'Very High',
    market_price: '₹15,000–25,000/quintal',
    image_url: 'https://images.unsplash.com/photo-1615485500704-8e990f9900f7?w=400&h=300&fit=crop',
    description: 'Aromatic rhizome used as spice and medicine; high export demand.',
  },
  {
    slug: 'cardamom',
    name: 'Cardamom (Elaichi)',
    scientific_name: 'Elettaria cardamomum',
    category: 'Spices',
    season: 'Perennial',
    water_need: 'High',
    climate: 'Tropical',
    region: 'Kerala, Karnataka, Sikkim',
    duration: 'Perennial',
    expected_yield: '0.1–0.2 tons/acre',
    difficulty: 'Hard',
    profitability: 'Very High',
    market_price: '₹80,000–1,20,000/quintal',
    image_url: 'https://images.unsplash.com/photo-1615485500704-8e990f9900f7?w=400&h=300&fit=crop',
    description: 'Queen of spices; shade-loving perennial with excellent market value.',
  },
  {
    slug: 'black_pepper',
    name: 'Black Pepper',
    scientific_name: 'Piper nigrum',
    category: 'Spices',
    season: 'Perennial',
    water_need: 'High',
    climate: 'Tropical',
    region: 'Kerala, Karnataka',
    duration: 'Perennial',
    expected_yield: '0.5–1.0 tons/acre',
    difficulty: 'Medium',
    profitability: 'Very High',
    image_url: 'https://images.unsplash.com/photo-1599909533601-91d62e5a5e03?w=400&h=300&fit=crop',
    description: 'King of spices; climbing vine producing peppercorns with strong flavor.',
  },
  {
    slug: 'coriander',
    name: 'Coriander (Dhania)',
    scientific_name: 'Coriandrum sativum',
    category: 'Spices',
    season: 'Rabi',
    water_need: 'Low',
    climate: 'Temperate',
    region: 'Rajasthan, MP, Gujarat',
    duration: '60–70 days',
    expected_yield: '0.5–0.8 tons/acre',
    difficulty: 'Easy',
    profitability: 'Medium',
    market_price: '₹6,000–8,000/quintal',
    image_url: 'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=400&h=300&fit=crop',
    description: 'Versatile herb used as spice and leafy green; fast-growing.',
  },
  {
    slug: 'cumin',
    name: 'Cumin (Jeera)',
    scientific_name: 'Cuminum cyminum',
    category: 'Spices',
    season: 'Rabi',
    water_need: 'Low',
    climate: 'Temperate',
    region: 'Rajasthan, Gujarat',
    duration: '100–120 days',
    expected_yield: '0.4–0.6 tons/acre',
    difficulty: 'Medium',
    profitability: 'Very High',
    market_price: '₹15,000–20,000/quintal',
    image_url: 'https://images.unsplash.com/photo-1596097635121-14b63a7b70b5?w=400&h=300&fit=crop',
    description: 'Essential spice with distinctive aroma; high export value.',
  },

  // === CASH CROPS (existing: sugarcane, cotton) ===
  {
    slug: 'tea',
    name: 'Tea',
    scientific_name: 'Camellia sinensis',
    category: 'Cash Crops',
    season: 'Perennial',
    water_need: 'High',
    climate: 'Tropical',
    region: 'Assam, Kerala, Darjeeling',
    duration: 'Perennial',
    expected_yield: '1,500–2,000 kg/acre',
    difficulty: 'Medium',
    profitability: 'High',
    image_url: 'https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=400&h=300&fit=crop',
    description: 'Major plantation crop; India is world\'s second-largest producer.',
  },
  {
    slug: 'coffee',
    name: 'Coffee',
    scientific_name: 'Coffea arabica',
    category: 'Cash Crops',
    season: 'Perennial',
    water_need: 'High',
    climate: 'Tropical',
    region: 'Karnataka, Kerala, Tamil Nadu',
    duration: 'Perennial',
    expected_yield: '800–1,200 kg/acre',
    difficulty: 'Hard',
    profitability: 'Very High',
    image_url: 'https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=400&h=300&fit=crop',
    description: 'Premium plantation crop; shade-grown under canopy trees.',
  },
  {
    slug: 'rubber',
    name: 'Rubber',
    scientific_name: 'Hevea brasiliensis',
    category: 'Cash Crops',
    season: 'Perennial',
    water_need: 'High',
    climate: 'Tropical',
    region: 'Kerala, Karnataka, Tamil Nadu',
    duration: 'Perennial',
    expected_yield: '1,500–2,000 kg/acre',
    difficulty: 'Medium',
    profitability: 'High',
    image_url: 'https://images.unsplash.com/photo-1583557965739-1a30f0a3b996?w=400&h=300&fit=crop',
    description: 'Important industrial crop; latex used in tire and rubber manufacturing.',
  },
  {
    slug: 'tobacco',
    name: 'Tobacco',
    scientific_name: 'Nicotiana tabacum',
    category: 'Cash Crops',
    season: 'Rabi',
    water_need: 'Medium',
    climate: 'Tropical',
    region: 'Andhra Pradesh, Gujarat, UP',
    duration: '90–120 days',
    expected_yield: '1.0–1.5 tons/acre',
    difficulty: 'Medium',
    profitability: 'High',
    image_url: 'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=400&h=300&fit=crop',
    description: 'Controversial but profitable cash crop; requires careful curing.',
  },
  {
    slug: 'jute',
    name: 'Jute',
    scientific_name: 'Corchorus olitorius',
    category: 'Cash Crops',
    season: 'Kharif',
    water_need: 'High',
    climate: 'Tropical',
    region: 'West Bengal, Bihar, Assam',
    duration: '120–150 days',
    expected_yield: '10–15 tons/acre',
    difficulty: 'Easy',
    profitability: 'Medium',
    image_url: 'https://images.unsplash.com/photo-1590005024862-6b67679a29fb?w=400&h=300&fit=crop',
    description: 'Golden fiber; eco-friendly natural fiber with growing demand.',
  },
  {
    slug: 'cotton',
    name: 'Cotton',
    scientific_name: 'Gossypium hirsutum',
    category: 'Cash Crops',
    season: 'Kharif',
    water_need: 'Medium',
    climate: 'Tropical',
    region: 'Gujarat, Maharashtra, Telangana',
    duration: '160–200 days',
    expected_yield: '2.8 quintals/acre',
    difficulty: 'Medium',
    profitability: 'High',
    market_price: '₹6,000–7,500/quintal',
    image_url: 'https://images.unsplash.com/photo-1502395809857-fd80069897d0?w=400&h=300&fit=crop',
    description: 'Commercial fiber crop with strong export demand; Bt hybrids reduce bollworm pressure.',
  },

  // === FRUITS (new category) ===
  {
    slug: 'mango',
    name: 'Mango',
    scientific_name: 'Mangifera indica',
    category: 'Fruits',
    season: 'Perennial',
    water_need: 'Medium',
    climate: 'Tropical',
    region: 'UP, Maharashtra, AP',
    duration: 'Perennial',
    expected_yield: '8–12 tons/acre',
    difficulty: 'Medium',
    profitability: 'Very High',
    image_url: 'https://images.unsplash.com/photo-1553279768-865429fa0078?w=400&h=300&fit=crop',
    description: 'King of fruits; India is world\'s largest producer.',
  },
  {
    slug: 'banana',
    name: 'Banana',
    scientific_name: 'Musa paradisiaca',
    category: 'Fruits',
    season: 'Perennial',
    water_need: 'High',
    climate: 'Tropical',
    region: 'Tamil Nadu, Maharashtra, UP',
    duration: 'Perennial',
    expected_yield: '20–30 tons/acre',
    difficulty: 'Medium',
    profitability: 'High',
    image_url: 'https://images.unsplash.com/photo-1528825871115-3581a5387919?w=400&h=300&fit=crop',
    description: 'Most popular fruit crop; quick returns with proper management.',
  },
  {
    slug: 'guava',
    name: 'Guava',
    scientific_name: 'Psidium guajava',
    category: 'Fruits',
    season: 'Perennial',
    water_need: 'Medium',
    climate: 'Tropical',
    region: 'UP, Maharashtra, AP',
    duration: 'Perennial',
    expected_yield: '10–15 tons/acre',
    difficulty: 'Easy',
    profitability: 'High',
    image_url: 'https://images.unsplash.com/photo-1536514498073-50e69d200b82?w=400&h=300&fit=crop',
    description: 'Hardy fruit tree; rich in Vitamin C with year-round production.',
  },
  {
    slug: 'papaya',
    name: 'Papaya',
    scientific_name: 'Carica papaya',
    category: 'Fruits',
    season: 'Perennial',
    water_need: 'Medium',
    climate: 'Tropical',
    region: 'Pan-India',
    duration: 'Perennial',
    expected_yield: '15–20 tons/acre',
    difficulty: 'Easy',
    profitability: 'High',
    image_url: 'https://images.unsplash.com/photo-1524179091875-bf99a9a6af57?w=400&h=300&fit=crop',
    description: 'Fast-growing fruit tree; first harvest within 8–10 months of planting.',
  },
  {
    slug: 'grapes',
    name: 'Grapes',
    scientific_name: 'Vitis vinifera',
    category: 'Fruits',
    season: 'Perennial',
    water_need: 'Medium',
    climate: 'Tropical',
    region: 'Maharashtra, AP, Karnataka',
    duration: 'Perennial',
    expected_yield: '8–12 tons/acre',
    difficulty: 'Hard',
    profitability: 'Very High',
    image_url: 'https://images.unsplash.com/photo-1537640538966-79f369143f8f?w=400&h=300&fit=crop',
    description: 'Premium fruit crop; table and wine varieties with excellent market value.',
  },
  {
    slug: 'orange',
    name: 'Orange',
    scientific_name: 'Citrus sinensis',
    category: 'Fruits',
    season: 'Perennial',
    water_need: 'Medium',
    climate: 'Tropical',
    region: 'Maharashtra, MP, Rajasthan',
    duration: 'Perennial',
    expected_yield: '10–15 tons/acre',
    difficulty: 'Medium',
    profitability: 'High',
    image_url: 'https://images.unsplash.com/photo-1547514701-42782101795e?w=400&h=300&fit=crop',
    description: 'Popular citrus fruit; high vitamin C content with good storage life.',
  },
  {
    slug: 'watermelon',
    name: 'Watermelon',
    scientific_name: 'Citrullus lanatus',
    category: 'Fruits',
    season: 'Kharif',
    water_need: 'High',
    climate: 'Tropical',
    region: 'Pan-India',
    duration: '80–95 days',
    expected_yield: '10–15 tons/acre',
    difficulty: 'Easy',
    profitability: 'High',
    image_url: 'https://images.unsplash.com/photo-1563114773-84221bd62daa?w=400&h=300&fit=crop',
    description: 'Refreshing summer fruit; quick maturing with high water content.',
  },
  {
    slug: 'apple',
    name: 'Apple',
    scientific_name: 'Malus domestica',
    category: 'Fruits',
    season: 'Perennial',
    water_need: 'Medium',
    climate: 'Temperate',
    region: 'HP, J&K, Uttarakhand',
    duration: 'Perennial',
    expected_yield: '10–15 tons/acre',
    difficulty: 'Hard',
    profitability: 'Very High',
    image_url: 'https://images.unsplash.com/photo-1570913149827-d2ac84ab3f9a?w=400&h=300&fit=crop',
    description: 'Major temperate fruit; premium market value in India.',
  },
  {
    slug: 'pomegranate',
    name: 'Pomegranate',
    scientific_name: 'Punica granatum',
    category: 'Fruits',
    season: 'Perennial',
    water_need: 'Low',
    climate: 'Tropical',
    region: 'Maharashtra, Rajasthan, AP',
    duration: 'Perennial',
    expected_yield: '8–10 tons/acre',
    difficulty: 'Medium',
    profitability: 'Very High',
    image_url: 'https://images.unsplash.com/photo-1541344999736-83eca272f6fc?w=400&h=300&fit=crop',
    description: 'Drought-tolerant fruit tree; high export demand for arils.',
  },
  {
    slug: 'citrus',
    name: 'Citrus (Lemon)',
    scientific_name: 'Citrus limon',
    category: 'Fruits',
    season: 'Perennial',
    water_need: 'Medium',
    climate: 'Tropical',
    region: 'Rajasthan, UP, MP',
    duration: 'Perennial',
    expected_yield: '6–8 tons/acre',
    difficulty: 'Medium',
    profitability: 'High',
    image_url: 'https://images.unsplash.com/photo-1590502593747-42a996133562?w=400&h=300&fit=crop',
    description: 'Versatile citrus fruit; essential for cooking and beverages.',
  },

  // === FIBER CROPS (new category) ===
  {
    slug: 'sisal',
    name: 'Sisal',
    scientific_name: 'Agave sisalana',
    category: 'Fiber Crops',
    season: 'Perennial',
    water_need: 'Low',
    climate: 'Tropical',
    region: 'Tamil Nadu, Karnataka',
    duration: 'Perennial',
    expected_yield: '1.5–2.0 tons/acre',
    difficulty: 'Easy',
    profitability: 'Medium',
    image_url: 'https://images.unsplash.com/photo-1590005024862-6b67679a29fb?w=400&h=300&fit=crop',
    description: 'Hardy fiber plant; drought-tolerant with multiple uses.',
  },

  // === LEGUME COVER CROPS ===
  {
    slug: 'mung_bean',
    name: 'Mung Bean',
    scientific_name: 'Vigna radiata',
    category: 'Pulses',
    season: 'Kharif',
    water_need: 'Low',
    climate: 'Tropical',
    region: 'Pan-India',
    duration: '60–70 days',
    expected_yield: '0.5–0.8 tons/acre',
    difficulty: 'Easy',
    profitability: 'Medium',
    image_url: 'https://images.unsplash.com/photo-1612257416648-ee7a4d709a24?w=400&h=300&fit=crop',
    description: 'Short-duration pulse; excellent for crop rotation.',
  },
];

function up(db) {
  if (!tableExists(db, 'plants')) {
    throw new Error('plants table missing — run migration 001 first.');
  }

  const insertPlant = db.prepare(`
    INSERT OR REPLACE INTO plants
      (slug, name, scientific_name, category, season, water_need, climate, region,
       duration, expected_yield, difficulty, profitability, market_price,
       image_url, description, overview_json, agronomy_json, pests_json, resources_json)
    VALUES
      (@slug, @name, @scientific_name, @category, @season, @water_need, @climate, @region,
       @duration, @expected_yield, @difficulty, @profitability, @market_price,
       @image_url, @description, @overview_json, @agronomy_json, @pests_json, @resources_json)
  `);

  let plantsTouched = 0;
  for (const p of EXPANDED_PLANTS) {
    insertPlant.run({
      ...p,
      market_price: p.market_price || 'Contact local market',
      overview_json: p.overview_json || JSON.stringify({}),
      agronomy_json: p.agronomy_json || JSON.stringify({}),
      pests_json: p.pests_json || JSON.stringify([]),
      resources_json: p.resources_json || JSON.stringify([]),
    });
    plantsTouched++;
  }

  return { plantsTouched };
}

module.exports = { up };
